# Generated by Django 5.1.2 on 2024-11-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpfcnpj', models.IntegerField(max_length=14)),
                ('end', models.CharField(max_length=100)),
                ('tel', models.IntegerField(max_length=15)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
