# Generated by Django 5.1.2 on 2024-11-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpfcnpj', models.IntegerField()),
                ('end', models.CharField(max_length=100)),
                ('tel', models.IntegerField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomemotor', models.CharField(max_length=50)),
                ('cilindrada', models.IntegerField()),
                ('combustivel', models.CharField(max_length=12)),
                ('tecnologia', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.FloatField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_final', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='orcamentos_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('orcamentos_end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.orcamentos')),
            ],
        ),
        migrations.CreateModel(
            name='pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('med', models.CharField(blank=True, max_length=10, null=True)),
                ('custo', models.FloatField(blank=True, null=True)),
                ('valor', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('aplic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.motor')),
            ],
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='buy_pecas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='principal.pecas'),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='ativos_servicos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='principal.servicos'),
        ),
    ]
