# Generated by Django 5.1.2 on 2024-11-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('dist', models.CharField(max_length=30)),
                ('quant', models.IntegerField()),
                ('custo', models.FloatField()),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.pecas')),
            ],
        ),
    ]
