# Generated by Django 5.1.2 on 2024-11-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomemotor', models.CharField(max_length=50)),
                ('cilindrada', models.IntegerField()),
                ('combustivel', models.CharField(max_length=12)),
                ('tecnologia', models.CharField(blank=True, max_length=20, null=True)),
                ('cilindros', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cpfcnpj',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='pecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField()),
                ('nome', models.CharField(max_length=30)),
                ('med', models.CharField(blank=True, max_length=10, null=True)),
                ('aplic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='principal.motor')),
            ],
        ),
    ]
